#!/usr/bin/env bash
set -uo pipefail
export LC_ALL=C
ROOT="${1:-.}"
cd "$ROOT" || exit 1
found=0
section() { printf "\n== %s\n" "$1"; }
report() { if [ -n "$1" ]; then echo "$1"; found=1; else echo "clean"; fi; }

dirs=(); for d in sections blocks snippets assets layout templates; do [ -d "$d" ] && dirs+=("$d"); done

section "Design-tool provenance (Figma, node IDs)"
report "$(grep -rniE 'figma|node[ -]?[0-9]+:[0-9]+' "${dirs[@]}" 2>/dev/null)"

section "AI or tool self-reference"
report "$(grep -rniE 'chatgpt|claude|copilot|cursor|generated by|ai-generated' "${dirs[@]}" 2>/dev/null)"

section "Test, debug or backup files"
report "$(find . -path ./node_modules -prune -o \( -iname '*.qa.js' -o -iname '*debug*' -o -iname '*.bak' -o -iname '*backup*' -o -iname '*.old' \) -print 2>/dev/null)"

section "Liquid comments other than {% doc %}"
report "$(grep -rnE '\{%-?\s*comment\s*-?%\}|\{%-?\s*#' sections blocks snippets layout 2>/dev/null)"

section "HTML comments"
report "$(grep -rn '<!--' sections blocks snippets layout 2>/dev/null)"

section "CSS and JS comments in source"
report "$(grep -rnE '/\*|(^|[^:])//' src sections blocks snippets --include='*.scss' --include='*.ts' --include='*.liquid' 2>/dev/null | grep -v 'https\?://' )"

section "Agency or client names in theme code and file names"
names='isourceit|isrc'
if [ -f docs/banned-names.txt ]; then
  extra=$(grep -v '^#' docs/banned-names.txt | grep -v '^\s*$' | paste -sd'|' -)
  [ -n "$extra" ] && names="$names|$extra"
fi
report "$( { grep -rniE "$names" "${dirs[@]}" config locales src 2>/dev/null; find sections blocks snippets templates assets src -type f 2>/dev/null | grep -iE "$names"; } | grep -v '^config/settings_data.json' )"

section "Hidden Figma characters (U+2028, U+00A0)"
report "$(grep -rn -e $'\xe2\x80\xa8' -e $'\xc2\xa0' sections blocks snippets templates locales config 2>/dev/null)"

echo
if [ "$found" -eq 1 ]; then
  echo "Hygiene: issues found. Read each hit in your diff and clean up before the PR."
  exit 1
fi
echo "Hygiene: clean."
